export const Constants = {
    SCENE_LOADER: "SCENE_LOADER",
    SCENE_MAIN: "SCENE_MAIN",


    SIMPLE_TOWER_1: "SIMPLE_TOWER_1",
    SIMPLE_BULLET: "SIMPLE_BULLET",

    SIMPLE_ENEMY: "SIMPLE_ENEMY",
    FAST_ENEMY: "FAST_ENEMY",
    ARMORED_ENEMY: "ARMORED_ENEMY",
    HEALER_ENEMY: "HEALER_ENEMY",
    BOSS_ENEMY: "BOSS_ENEMY"
}