import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";

const PhaserGameNoSSR = dynamic(() => import("../game/game"), {
  ssr: false,
});
const PhaserGamePage: NextPage = () => <PhaserGameNoSSR />;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tower Farmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PhaserGamePage />
      </main>
    </div>
  );
};

export default Home;
